version: '3'
services:
  dockerapp:
    build: .
    container_name: dockerapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s